### ISSUE TITLE
About Question with depth

### ISSUE THREAD

**Issue by starhiking** [apchenstu/mvsnerf#16]
Reference to your readme,  while the command `CUDA_VISIBLE_DEVICES=0  python train_mvs_nerf_pl.py
    --with_depth  --imgScale_test 1.0 \
    --expname mvs-nerf-is-all-your-need \
    --num_epochs 6 --N_samples 128 --use_viewdirs --batch_size 1024 \
    --dataset_name dtu \
    --datadir path/to/dtu/data \
    --N_vis 6` cannot work.

Error information :

log['val_psnr'] = mse2psnr(torch.mean(img_err_abs[:,mask] ** 2))
IndexError: The shape of the mask [1, 1] at index 0 does not match the shape of the indexed tensor [3, 512, 640] at index1

**Comment by apchenstu** [comment]
It may be caused by the resolution issue, please download the Depth_raw from the original MVSNet repo or just remove the "--with_depth" command

**Comment by leo-frank** [comment]
> It may be caused by the resolution issue, please download the Depth_raw from the original MVSNet repo or just remove the "--with_depth" command

where is Depth_raw from the original MVSNet repo?
