### ISSUE TITLE
What's the fps during inference?

### ISSUE THREAD

**Issue by chenerg** [apchenstu/mvsnerf#2]

**Comment by apchenstu** [comment]
Hi there, our mvsnerf doesn't focus on speeding up the rendering time so the rendering time is equally with meta nerf. But i think it can be easily combined with [plenoctrees](https://alexyu.net/plenoctrees) to speed up the rendering time. Thanks.

**Comment by SSground** [comment]
> _No description provided._

I have the same problem, have you combined the two(mvsnerf and plenoctree)? Can you leave a mailbox to facilitate communication？220162757@seu.edu.cn
