### ISSUE TITLE
How to derive homographic warping formula in section 3.1

### ISSUE THREAD

**Issue by murumura** [apchenstu/mvsnerf#23]
Hi, thank you for sharing the cool work. 
I am wondering how to derive the matrix warping formula in section 3.1 i.e 

![2021-09-21_17-06](https://user-images.githubusercontent.com/38805921/134143870-05c31f8e-e0d9-49b2-a618-1394a82f7013.png)

Because according to my own derivation, the result is

![CodeCogsEqn (1)](https://user-images.githubusercontent.com/38805921/134149347-59b84645-277b-410d-951b-8d9febf6d148.gif)

Are there any derivation premises that I have not considered? Thanks in advance

**Comment by dwangxxx** [comment]
I think this formula is from this paper https://arxiv.org/pdf/1804.02505.pdf. Actually, this formula is wrong, so.....
You can watch this video for more details. https://www.youtube.com/watch?v=zmE_kj-Gh84

**Comment by kwea123** [comment]
Yes, and an easier way to think is by backprojection and reprojection, not by R and T directly.

**Comment by apchenstu** [comment]
Oh, thanks for pointing out that!

**Comment by murumura** [comment]
thanks for reply, i'm closing the issue
