### ISSUE TITLE
What is train_mvs_nerf_fusion_finetuning_pl.py used for?

### ISSUE THREAD

**Issue by FreemanG** [apchenstu/mvsnerf#25]
Thanks for your nice work!

What is `train_mvs_nerf_fusion_finetuning_pl.py` for when there is already a `train_mvs_nerf_finetuning_pl.py` ?

**Comment by apchenstu** [comment]
Oh, I forgot to remove this file, it's used for some fusion experiments, you can just bypass this file.

**Comment by FreemanG** [comment]
Thanks for your reply.
