### ISSUE TITLE
Fine-tuning the problem

### ISSUE THREAD

**Issue by SSground** [apchenstu/mvsnerf#31]
![image](https://user-images.githubusercontent.com/27821863/139666389-3fe75754-90c9-4ee9-845a-78c7ee08a81e.png)

When I try finetune, the following error appears, how can I solve this?

**Comment by cduguet** [comment]
This is because the scene name is taken from your path, and if your path ends with `/`, then it will recognize the scene as `""`. Delete the trailing `/`.

**Comment by SSground** [comment]
> This is because the scene name is taken from your path, and if your path ends with `/`, then it will recognize the scene as `""`. Delete the trailing `/`.

![image](https://user-images.githubusercontent.com/27821863/144957382-64fa73c5-6aed-418c-b89e-a3c5e5a7fcdd.png)
Delete the trailing / 
This problem occurred after deleting

**Comment by apchenstu** [comment]
> > This is because the scene name is taken from your path, and if your path ends with `/`, then it will recognize the scene as `""`. Delete the trailing `/`.
> 
> ![image](https://user-images.githubusercontent.com/27821863/144957382-64fa73c5-6aed-418c-b89e-a3c5e5a7fcdd.png) Delete the trailing / This problem occurred after deleting

the name should be something like "room_train" instead of "room_2v_train"

**Comment by SSground** [comment]
> > > This is because the scene name is taken from your path, and if your path ends with `/`, then it will recognize the scene as `""`. Delete the trailing `/`.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/27821863/144957382-64fa73c5-6aed-418c-b89e-a3c5e5a7fcdd.png) Delete the trailing / This problem occurred after deleting
> 
> the name should be something like "room_train" instead of "room_2v_train"

I have solved this problem, thanks for reply
