### ISSUE TITLE
Enquiry into dtu_pairs.txt file

### ISSUE THREAD

**Issue by mckhang** [apchenstu/mvsnerf#32]
Hi, thanks for your great work. 
I would like to make an enquiry into how dtu_pairs.txt file was created (not pairs.th file) and especially into what the floating point values mean in each line.

Thank you

**Comment by vyang16** [comment]
It seems to be taken from [MVSNet](https://github.com/YoYo000/MVSNet#view-selection-file), and they have a description of the pairs.txt file format there. 
You can also find their view selection score computation (the floating point values) in [`colmap2mvsnet.py`](https://github.com/YoYo000/MVSNet/blob/3ae2cb2b72c6df58ebcb321d7d243d4efd01fbc5/mvsnet/colmap2mvsnet.py#L383)

**Comment by mckhang** [comment]
Got it. Wasn't aware that the two txt files were referring to the same thing. Thanks for the information!
