### ISSUE TITLE
Some questions about code details and abnormal phenomenon

### ISSUE THREAD

**Issue by Impuuuuuu** [apchenstu/mvsnerf#39]
Hi, it's very kind of you for releasing the code of the paper, and there are some questions about code details and abnormal phenomenon:

1.
![image](https://user-images.githubusercontent.com/46101750/144568368-ca57821d-dbac-4a62-9237-443cc63f369a.png)
![image](https://user-images.githubusercontent.com/46101750/144568651-50ef79cf-f994-4084-a148-2548ddf461c4.png)
As is shown in the first image, I am bit confused of the codes in 140-144 lines of ./data/dtu.py. The reference should be the first element of "view_ids", the in codes in 140-144 lines you have put in the last position. Is something wrong with my understanding?

2. 
![image](https://user-images.githubusercontent.com/46101750/144569448-74b20b60-8ca5-4f81-9ba2-8297a3ccce60.png)
And again in the codes in 233-234 lines of ./train_mvs_nerf_pl.py, here appears two notions, tgt and ref. So may I ask what exactly src, ref, and tgt stands for?

3. 
Is the "with_depth" option means that we have got the depth map of dataset and we should not activate it if we do not get the depth map?

4. 
![image](https://user-images.githubusercontent.com/46101750/144570488-66a6b52e-9eae-4891-86d1-241a0f9141ed.png)
Last qusetion, when I train with my own dataset, nan appears after a few iterations. Have you ever met with the same problem?

Looking forward to your answers. Thanks for your work again.

**Comment by apchenstu** [comment]
Hi, thanks, 1. we define the 'reference view' (mostly used in other papers) to be target view, so we put it at the last, and randomly select 3 views to the source views. 2. please refer to the figure of our pipeline, 3. that's right, 4. oh, I didn't train this model with other datasets, so I don't have much sense on this issue. I think you can try to overfitting on a single scene, I believe this can help you for debugging.

**Comment by Impuuuuuu** [comment]
> Hi, thanks, 1. we define the 'reference view' (mostly used in other papers) to be target view, so we put it at the last, and randomly select 3 views to the source views. 2. please refer to the figure of our pipeline, 3. that's right, 4. oh, I didn't train this model with other datasets, so I don't have much sense on this issue. I think you can try to overfitting on a single scene, I believe this can help you for debugging.

Thanks for your reply quite a lot!
