### ISSUE TITLE
Intrinsic preprocessing

### ISSUE THREAD

**Issue by phongnhhn92** [apchenstu/mvsnerf#41]
Hello, I have been using your dataloader but I've seen some weird preprocessing you have done. As I recall the training image size is (512,640). Why would you multiply fx, fy, cx, cy by 4 times in this line of code 
https://github.com/apchenstu/mvsnerf/blob/6e0111188ff92b13229482a95a2fb4eaddbc2971/data/dtu.py#L83

Moreover, later on, you divide the intrinsic again to 4 to produce the projection matrix of each view. Then why would you multiply the intrinsic with 4 in the beginning ?

**Comment by markomih** [comment]
The loaded camera model seems to be for 1/4 of the original resolution, hence multiplied by 4.  
Afterward, the intrinsics are divided by 4 in order to compute projection matrices for the feature maps which are 1/4 of the original image resolution.

**Comment by phongnhhn92** [comment]
> The loaded camera model seems to be for 1/4 of the original resolution, hence multiplied by 4. Afterward, the intrinsics are divided by 4 in order to compute projection matrices for the feature maps which are 1/4 of the original image resolution.

Hi, I understand why he has to divide by 4 because of the size of the feature maps. However, if we compare this with CasMVS repo then it still doesnt make sense to me. https://github.com/kwea123/CasMVSNet_pl/blob/5813306b451b22226a321d347e5f6020a20ae8c9/datasets/dtu.py#L60
