### ISSUE TITLE
Own dataset test.

### ISSUE THREAD

**Issue by dwangxxx** [apchenstu/mvsnerf#5]
Hi, thanks for your source code. Could you tell me how can I generate my own dataset？Use colmap or some others？Thank you！

**Comment by apchenstu** [comment]
yeah, you can calibrate the image with the COLMAP or other tools, after calibration you have the extrinsic and intrinsic and near-far , then you can convert it to the blender, llff or dtu format. This [repo](https://github.com/Fyusion/LLFF) provides guidance from COLMAP to LLFF format.

**Comment by dwangxxx** [comment]
Thanks very much. I'll close this issue.
