### ISSUE TITLE
few views in training

### ISSUE THREAD

**Issue by caiyongqi** [apchenstu/mvsnerf#54]
In dtu.py: 
```
if self.split=='train':
    ids = torch.randperm(5)[:3]
    view_ids = [src_views[i] for i in ids] + [target_view]
```
It seems that only a small number of images are used for training in the dtu dataset?

**Comment by caiyongqi** [comment]
Why use torch.randperm(5)?

**Comment by apchenstu** [comment]
Hi, the `ids = torch.randperm(5)[:3]` refers to selecting 3 source views from its 5 neighboring views for each training image. Thanks!
