### ISSUE TITLE
Save evaluation results?

### ISSUE THREAD

**Issue by sergeyprokudin** [apchenstu/mvsnerf#59]
Hi, 

thanks for sharing the work! The [link](https://drive.google.com/drive/folders/1ko8OW38iDtj4fHvX0e3Wom9YvtJNTSXu?usp=sharing) to evaluation results seem to be broken, can you please re-upload? Thanks!

-Sergey

**Comment by apchenstu** [comment]
Hi Sergey, great to meet you here and sorry about my late reply due to getting stuck by other things. I deleted them by mistake and here is a new link for reference: https://1drv.ms/u/s!Ard0t_p4QWIMiBrhAm0QnP80zOCH?e=hWSNny

**Comment by sergeyprokudin** [comment]
Hi Anpei, thanks a lot for looking into this and re-uploading :) 

~Sergey

**Comment by 19991105** [comment]
> Hi Sergey, great to meet you here and sorry about my late reply due to getting stuck by other things. I deleted them by mistake and here is a new link for reference: https://1drv.ms/u/s!Ard0t_p4QWIMiBrhAm0QnP80zOCH?e=hWSNny

Hi,The video in this link can't open again,can you please upload it one more time?Thanks a lot!
