### ISSUE TITLE
Cannot reproduce the results on LLFF dataset

### ISSUE THREAD

**Issue by cwchenwang** [apchenstu/mvsnerf#69]
Hi, I used your code in `render.ipynb` and tried to evaluate the pretrained model on LLFF, but I found the metrics are significant lower than that reported in the paper, for example: for the room scene, the result PSNR are only 22.99, but in the paper it is 26.95.

<img width="1342" alt="Screen Shot 2022-08-24 at 9 27 17 PM" src="https://user-images.githubusercontent.com/23579918/186430572-7614b455-69a8-4b3f-93bb-27bfebc80661.png">

**Comment by Deng-shangqi** [comment]
> Hi, I used your code in `render.ipynb` and tried to evaluate the pretrained model on LLFF, but I found the metrics are significant lower than that reported in the paper, for example: for the room scene, the result PSNR are only 22.99, but in the paper it is 26.95.
> 
> <img alt="Screen Shot 2022-08-24 at 9 27 17 PM" width="1342" src="https://user-images.githubusercontent.com/23579918/186430572-7614b455-69a8-4b3f-93bb-27bfebc80661.png">

May I ask which dataset you used for pretraining

**Comment by cwchenwang** [comment]
> > Hi, I used your code in `render.ipynb` and tried to evaluate the pretrained model on LLFF, but I found the metrics are significant lower than that reported in the paper, for example: for the room scene, the result PSNR are only 22.99, but in the paper it is 26.95.
> > <img alt="Screen Shot 2022-08-24 at 9 27 17 PM" width="1342" src="https://user-images.githubusercontent.com/23579918/186430572-7614b455-69a8-4b3f-93bb-27bfebc80661.png">
> 
> May I ask which dataset you used for pretraining

I used the provided checkpoints, but the problem is solved now by changing the configs.

**Comment by h5jam** [comment]
@cwchenwang Hi, I faced with the same problem. Can I ask you for modified configs?
